### ISSUE TITLE
Addon availability

### ISSUE THREAD

**Issue by metasean** [goooseman/storybook-addon-i18n#16]
@goooseman  - This addon is still listed on the Storybook website's [Addons page](https://storybook.js.org/addons/) (which is how I ended up here).

But you mention at the top of your readme:
>Warning! PR's will be reviewed and accepted, but this library is deprecated in favor of using [Storybook Addon Contexts](https://github.com/storybookjs/storybook/tree/master/addons/contexts), which can be used in the following way...  

(Which is totally understandable.)

Unfortunately the "Storybook Addon Contexts" link in that warning is broken, and there doesn't appear to be a "Context" plugin in the Adds-on available from the Storybook repo - https://github.com/storybookjs/storybook/tree/next/addons

Do you know if the "Internationalization" option in the "Toolbars" addon [[1](https://storybook.js.org/docs/react/essentials/toolbars-and-globals#advanced-usage), [2](https://github.com/storybookjs/storybook/blob/master/addons/toolbars/README.md)] is the replacement for the "Context" plugin that you mentioned?

If you are abandoning maintenance of this repo, it would be nice if that was evident via the https://storybook.js.org/addons/ page , instead of other people also making this journey.  😉

**Comment by goooseman** [comment]
Hi! Thanks for the info.

1. A PR to delete `i18n` from addons page is created: https://github.com/storybookjs/frontpage/pull/173
2. Yep, you can use Storybook 6 to have this functionality with some little extra configuration using:
  - https://storybook.js.org/docs/react/writing-stories/decorators#context-for-mocking
  - https://storybook.js.org/docs/react/essentials/toolbars-and-globals#advanced-usage

I did not try, but by looking at documentation I see a following configuration:


```
// .storybook/preview.js

export const globalTypes = {
  locale: {
    name: 'Locale',
    description: 'Internationalization locale',
    defaultValue: 'en',
    toolbar: {
      icon: 'globe',
      items: [
        { value: 'en', right: '🇺🇸', title: 'English' },
        { value: 'fr', right: '🇫🇷', title: 'Français' },
        { value: 'es', right: '🇪🇸', title: 'Español' },
        { value: 'zh', right: '🇨🇳', title: '中文' },
        { value: 'kr', right: '🇰🇷', title: '한국어' },
      ],
    },
  },
};

export const decorators = [
  (Story, { globals }) => (
    <YourI18nProvider locale={globals.locale} translations={translations}">
      <Story />
    </YourI18nProvider>
  ),
];
```

**Comment by goooseman** [comment]
The README of this project is also updated
