### ISSUE TITLE
I cannot get this to work, the addon is never registered

### ISSUE THREAD

**Issue by tomitrescak** [goooseman/storybook-addon-i18n#3]
I have followed your instructions but I cannot get this to work.
When I debug it, the following function is never called:

```
private onRegister = (parameters: Parameters) => {
    const defaultLocale = this.getDefaultLocale(parameters.supportedLocales);
    this.setState({
      locales: parameters.supportedLocales
    });
    this.changeLocale(defaultLocale);
  };
```

**Comment by alexeychikk** [comment]
@tomitrescak Could you please provide the code you use to setup the addon?
In the meantime, make sure you add `import "storybook-addon-i18n/register.js";` to your `.storybook/addons.js` as described in the readme.

**Comment by tomitrescak** [comment]
I just followed your guide. And used my Provider.

This is all the code I used:

Create a file called addons.js in your Storybook config, if there is no any and append following line:

// addons.js
import "storybook-addon-i18n/register.js";

Then in your story's config or in a global config for the project (config.js) add i18n key to parameters:

// config.js
import { addParameters } from "@storybook/react";

addParameters({
  i18n: {
    provider: LionessProvider,
    providerProps: {
      messages,
    },
    supportedLocales: ["en", "ru"],
    providerLocaleKey: "locale"
  },
});

**Comment by goooseman** [comment]
@tomitrescak And is [this line](https://github.com/goooseman/storybook-addon-i18n/blob/c3faf19ac939341133868d245b6d5f9f0b2b06af/src/LocaleSelector.tsx#L27) is called when you debug your storybook?

The only reason I see for a behavior like this is register import (`import "storybook-addon-i18n/register.js"`) is not fired. Are you sure, that you have placed it inside `.storybook/addons.js` and the filename is exactly the same?

Try to copy this line: `cat .storybook/addons.js` and paster it in the terminal in the root of your project. Do you see the correct output?

And what version of storybook are you using?

**Comment by tomitrescak** [comment]
Yes, the registration is fired. I'm using version 5.1. Same as referenced in your package.json (you should probably remove exact naming BTW, from '5.1.x' to '^5.1.x').

In the end I gutted out your functionality and adjusted it for my needs (thanks for the amazing code, which saved me myriads of time). In order not to waste your time, let's close this issue. If someone else reports this I'll try to create reproducible case. For now I'm fine.

**Comment by alexeychikk** [comment]
@tomitrescak Sorry, we have missed one step to setup the addon that is described in this PR: https://github.com/goooseman/storybook-addon-i18n/pull/5/files

> **Finally, Add decorator in your story's config or in a global config for the project (`config.js`)**

```ts
// config.js
import { addDecorator } from "@storybook/react";
import { withI18n } from "storybook-addon-i18n";

addDecorator(withI18n);
```
