### ISSUE TITLE
Direction detection is unreliable

### ISSUE THREAD

**Issue by alexeychikk** [goooseman/storybook-addon-i18n#4]
This line is unreliable to be used as direction detection.
https://github.com/goooseman/storybook-addon-i18n/blob/c3faf19ac939341133868d245b6d5f9f0b2b06af/src/Provider.tsx#L65
Please consider using the following:
https://github.com/trucknet-io/react-targem/blob/develop/src/utils/constants.ts#L1

**Comment by goooseman** [comment]
Resolved in #7
